### ISSUE TITLE
Notifications stay visible for too long and create backlog

### ISSUE THREAD

**Issue by n4n0GH** [mantso/f3d-issues#13]
With the testnet we've seen a massive increase in interactions and a delay in actual displayed events inside the notifications because they currently stay visible for a fixed amount of time but should be removed if newer notifs roll in to not create a massive backlog that does not reflect the current state of the game.

**Comment by mantso** [comment]
Low priority. The header will always display the correct information, the order of the notifications is less important as they are not integral to the game.
