### ISSUE TITLE
Contract Draining Time issue

### ISSUE THREAD

**Issue by traboprovod** [mantso/f3d-issues#6]
![bug](https://user-images.githubusercontent.com/39992563/41037012-8d4610b8-69c4-11e8-9724-c4f5bbefe44e.png)

contract draining
it says 4 hours instead of 90sec :(

**Comment by mantso** [comment]
Thank you for reporting. We know why this is. The website uses the local time of your computer as a "starting point". That means if the computer time is not in sync, the timer on the website will not be either. A fix is in the works right now.

**Comment by mantso** [comment]
Fixed.
