### ISSUE TITLE
Team selection should persist across browsing sessions.

### ISSUE THREAD

**Issue by ARitz-Cracker** [mantso/f3d-issues#7]
I slept, woke up, I forgot that team snek is default and I wanted whale. Guess my 1000ETH pump gues to P3D Holders nowowowwwww
cum on manster you  can JS Store step it uppppppppp

**Comment by n4n0GH** [comment]
Easy fix would be with local storage, however that'd impede people using multiple devices.

**Comment by mantso** [comment]
Fixed.
